language: c

dist: bionic

env:
  matrix:
    #- FEDORA_KIND="releases" FEDORA_MAJOR="32"
    - FEDORA_KIND="development" FEDORA_MAJOR="rawhide"

addons:
  apt:
    packages:
      - qemu-kvm
      - libvirt-bin
      - virtinst
      - bridge-utils
      - libguestfs-tools
      - cpu-checker

before_install:
  - sudo usermod -a -G kvm,libvirt,libvirt-qemu "$USER"
  # Verify that KVM is working, useful if Travis ever changes anything.
  - kvm-ok
  - sudo systemctl enable libvirtd
  - sudo systemctl start libvirtd
  # Set up a key so we can ssh into the VM
  - ssh-keygen -N "" -f "$HOME/.ssh/id_rsa"

script:
  - bash travis-ci/run-kvm-test.sh travis-ci/run-testsuite.sh
